name: pushe_flutter
description: Official pushe.co plugin for flutter
version: 2.0.0
authors:
  - Pushe <mahdi.malvandi@pushe.co>
homepage: https://pushe.co

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: co.pushe.plus.flutter
    pluginClass: PushePlugin
