name: pushe_flutter
description:  Pushe push notification SDK implementation for Flutter framework, for Android and iOS
version: 2.4.0
homepage: https://pushe.co
documentation: https://docs.pushe.co/docs/flutter/intro/
issue_tracker: https://github.com/pusheco/pushe-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: co.pushe.plus.flutter
        pluginClass: PusheFlutterPlugin
      ios:
        pluginClass: PusheFlutterPlugin