name: pushe_flutter
description: Pushe push notification SDK implementation for Flutter framework, for Android and iOS
version: 2.0.3
authors:
  - Pushe <mahdi.malvandi@pushe.co>
homepage: https://pushe.co

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: co.pushe.plus.flutter
    pluginClass: PushePlugin
