name: pushe_flutter
description: Pushe push notification SDK implementation for Flutter framework, for Android and iOS
version: 2.1.1-alpha01
homepage: https://pushe.co

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: co.pushe.plus.flutter
        pluginClass: PushePlugin
      ios:
        pluginClass: PushePlugin

